import { useEffect, useState } from 'react';
import type { SessionWeeks } from '../autogen/config';

export type AutoGenerateMode = 'fill-empty' | 'replace-all';
/** What to do with one week when generating the whole session. */
export type WeekChoice = 'lock' | AutoGenerateMode;

/** What the dialog needs to know about each week slot. */
export interface WeekInfo {
  hasBunks: boolean;
  hasActivities: boolean;
  /** Already filled in (few empty periods). Such a week starts out locked. */
  built: boolean;
}

/** What the user asked for. `weeks` lists the weeks to generate, in order, with 0-based indexes. */
export interface AutoGeneratePlan {
  sessionWeeks: SessionWeeks;
  /** When replacing: leave Bike Trip and Tiyul where they are. */
  keepTrips: boolean;
  /** Take the weeks that are not being generated into account, so totals and visit numbers stay consistent with them. */
  useOtherWeeks: boolean;
  weeks: { index: number; mode: AutoGenerateMode }[];
}

interface Props {
  /** 1-based number of the selected week. */
  weekNumber: number;
  /** Does the selected week already have any activities in it? */
  hasActivities: boolean;
  /** Every week slot, in order. When given, the dialog also offers the whole session. */
  weeks?: WeekInfo[];
  onCancel: () => void;
  onGenerate: (plan: AutoGeneratePlan) => void;
}

const defaultChoice = (w: WeekInfo): WeekChoice => (w.built ? 'lock' : w.hasActivities ? 'fill-empty' : 'replace-all');

/** Confirm dialog for Auto generate: one week or the whole session, what to do with what is already there, and which session it is. */
export default function AutoGenerateDialog({ weekNumber, hasActivities, weeks = [], onCancel, onGenerate }: Props) {
  const [scope, setScope] = useState<'week' | 'session'>('week');
  const [mode, setMode] = useState<AutoGenerateMode>('fill-empty');
  const [sessionWeeks, setSessionWeeks] = useState<SessionWeeks>(4);
  const [keepTrips, setKeepTrips] = useState(true);
  const [useOtherWeeks, setUseOtherWeeks] = useState(true);
  const [choices, setChoices] = useState<WeekChoice[]>(() => weeks.map(defaultChoice));

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onCancel();
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [onCancel]);

  const inSession = weeks.slice(0, sessionWeeks);
  const sessionPlan = inSession.map((_, index) => ({ index, choice: choices[index] })).filter((w) => w.choice !== 'lock');
  const replacing = scope === 'week' ? mode === 'replace-all' && hasActivities : sessionPlan.some((w) => w.choice === 'replace-all' && inSession[w.index].hasActivities);
  const nothingToDo = scope === 'session' && sessionPlan.length === 0;

  const generate = () => {
    const list =
      scope === 'week'
        ? [{ index: weekNumber - 1, mode: hasActivities ? mode : ('replace-all' as AutoGenerateMode) }]
        : sessionPlan.map((w) => ({ index: w.index, mode: w.choice as AutoGenerateMode }));
    onGenerate({ sessionWeeks, keepTrips, useOtherWeeks, weeks: list });
  };

  const title = scope === 'week' ? `Auto generate Week ${weekNumber}?` : 'Auto generate the session?';
  return (
    <div className="modal-backdrop" onMouseDown={(e) => e.target === e.currentTarget && onCancel()}>
      <div className="modal" role="dialog" aria-modal="true" aria-labelledby="autogen-title">
        <h2 id="autogen-title">{title}</h2>
        <p>
          This builds the periods from the bunks on the Build tab. Put in the Tusc bike trip and any Tiyul first: Auto generate
          never adds those, it builds around them. It reads the other weeks you have loaded, so each bunk&apos;s totals stay fair
          across the whole session. Every time you run it you get a different valid schedule, so you can keep regenerating until
          you like one.
        </p>

        {weeks.length > 0 && (
          <fieldset>
            <legend>What should be generated?</legend>
            <label>
              <input type="radio" name="autogen-scope" checked={scope === 'week'} onChange={() => setScope('week')} /> Just Week {weekNumber}
            </label>
            <label>
              <input type="radio" name="autogen-scope" checked={scope === 'session'} onChange={() => setScope('session')} /> The whole
              session, week by week
            </label>
          </fieldset>
        )}

        {scope === 'week' && hasActivities && (
          <fieldset>
            <legend>Week {weekNumber} already has activities in it. What should happen to them?</legend>
            <label>
              <input type="radio" name="autogen-mode" checked={mode === 'fill-empty'} onChange={() => setMode('fill-empty')} /> Keep what
              is there and build around it. Only the empty periods are filled.
            </label>
            <label>
              <input type="radio" name="autogen-mode" checked={mode === 'replace-all'} onChange={() => setMode('replace-all')} /> Replace
              what is there. Week {weekNumber} is cleared first.
            </label>
          </fieldset>
        )}

        {scope === 'session' && (
          <fieldset>
            <legend>What should happen to each week?</legend>
            {inSession.map((w, index) => (
              <label key={index}>
                Week {index + 1}{' '}
                <select
                  value={choices[index]}
                  onChange={(e) => setChoices((list) => list.map((c, i) => (i === index ? (e.target.value as WeekChoice) : c)))}
                >
                  <option value="lock">Lock: leave it exactly as it is</option>
                  <option value="fill-empty">Build around what is there</option>
                  <option value="replace-all">Regenerate: clear it and build it again</option>
                </select>
                {!w.hasBunks && choices[index] !== 'lock' && <span className="muted"> uses Week {weekNumber}&apos;s bunks</span>}
              </label>
            ))}
          </fieldset>
        )}

        <fieldset>
          <legend>Options</legend>
          <label>
            <input type="checkbox" checked={keepTrips} disabled={!replacing} onChange={(e) => setKeepTrips(e.target.checked)} /> When
            replacing, keep Bike Trip and Tiyul where they are.
          </label>
          <label>
            <input type="checkbox" checked={useOtherWeeks} onChange={(e) => setUseOtherWeeks(e.target.checked)} /> Stay consistent with
            the weeks that are not being generated. Untick to start fresh, as if those weeks were not there.
          </label>
        </fieldset>

        <p>
          <label>
            Session{' '}
            <select value={sessionWeeks} onChange={(e) => setSessionWeeks(Number(e.target.value) === 3 ? 3 : 4)}>
              <option value={4}>Session 1 (4 weeks)</option>
              <option value={3}>Session 2 (3 weeks)</option>
            </select>
          </label>
        </p>

        <div className="modal-buttons">
          <button type="button" onClick={onCancel}>
            Cancel
          </button>{' '}
          <button type="button" className="primary" autoFocus disabled={nothingToDo} onClick={generate}>
            Generate
          </button>
        </div>
      </div>
    </div>
  );
}
