import { useEffect, useState } from 'react';
import type { SessionWeeks } from '../autogen/config';

export type AutoGenerateMode = 'fill-empty' | 'replace-all';

interface Props {
  /** 1-based number of the week being generated. */
  weekNumber: number;
  /** Does the week already have any activities in it? */
  hasActivities: boolean;
  onCancel: () => void;
  /** keepTrips only matters when replacing: leave Bike Trip and Tiyul where they are. */
  onGenerate: (mode: AutoGenerateMode, sessionWeeks: SessionWeeks, keepTrips: boolean) => void;
}

/** Confirm dialog for Auto generate: asks what to do with what is already filled in, and which session it is. */
export default function AutoGenerateDialog({ weekNumber, hasActivities, onCancel, onGenerate }: Props) {
  const [mode, setMode] = useState<AutoGenerateMode>('fill-empty');
  const [sessionWeeks, setSessionWeeks] = useState<SessionWeeks>(4);
  const [keepTrips, setKeepTrips] = useState(true);

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onCancel();
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [onCancel]);

  const title = `Auto generate Week ${weekNumber}?`;
  return (
    <div className="modal-backdrop" onMouseDown={(e) => e.target === e.currentTarget && onCancel()}>
      <div className="modal" role="dialog" aria-modal="true" aria-labelledby="autogen-title">
        <h2 id="autogen-title">{title}</h2>
        <p>
          This builds the periods for Week {weekNumber} from the bunks on the Build tab. Put in the Tusc bike trip and any Tiyul
          first: Auto generate never adds those, it builds around them. It reads the other weeks you have loaded, so each
          bunk&apos;s totals stay fair across the whole session. Every time you run it you get a different valid schedule, so you
          can keep regenerating until you like one.
        </p>

        {hasActivities && (
          <fieldset>
            <legend>Week {weekNumber} already has activities in it. What should happen to them?</legend>
            <label>
              <input type="radio" name="autogen-mode" checked={mode === 'fill-empty'} onChange={() => setMode('fill-empty')} /> Keep what
              is there and build around it. Only the empty periods are filled.
            </label>
            <label>
              <input type="radio" name="autogen-mode" checked={mode === 'replace-all'} onChange={() => setMode('replace-all')} /> Replace
              what is there. Week {weekNumber} is cleared first.
            </label>
            <label className="sub-option">
              <input type="checkbox" checked={keepTrips} disabled={mode !== 'replace-all'} onChange={(e) => setKeepTrips(e.target.checked)} /> When
              replacing, keep Bike Trip and Tiyul where they are.
            </label>
          </fieldset>
        )}

        <p>
          <label>
            Session{' '}
            <select value={sessionWeeks} onChange={(e) => setSessionWeeks(Number(e.target.value) === 3 ? 3 : 4)}>
              <option value={4}>Session 1 (4 weeks)</option>
              <option value={3}>Session 2 (3 weeks)</option>
            </select>
          </label>
        </p>

        <div className="modal-buttons">
          <button type="button" onClick={onCancel}>
            Cancel
          </button>{' '}
          <button type="button" className="primary" autoFocus onClick={() => onGenerate(hasActivities ? mode : 'replace-all', sessionWeeks, keepTrips)}>
            Generate
          </button>
        </div>
      </div>
    </div>
  );
}
