import { useEffect, useState } from 'react';
import type { SessionWeeks } from '../autogen/config';

export type AutoGenerateMode = 'fill-empty' | 'replace-all';
/** What to do with one week when generating the whole session. */
export type WeekChoice = 'lock' | AutoGenerateMode;

/** What the dialog needs to know about each week slot. */
export interface WeekInfo {
  hasBunks: boolean;
  hasActivities: boolean;
  /** Already filled in (few empty periods). Such a week starts out locked. */
  built: boolean;
}

/** What the user asked for. `weeks` lists the weeks to generate, in order, with 0-based indexes. */
export interface AutoGeneratePlan {
  sessionWeeks: SessionWeeks;
  /** When replacing: leave Bike Trip and Tiyul where they are. */
  keepTrips: boolean;
  /** Take the weeks that are not being generated into account, so totals and visit numbers stay consistent with them. */
  useOtherWeeks: boolean;
  /** Leave the days that have already happened (through today) exactly as they are. */
  keepPast: boolean;
  weeks: { index: number; mode: AutoGenerateMode }[];
}

interface Props {
  /** 1-based number of the selected week. */
  weekNumber: number;
  /** Does the selected week already have any activities in it? */
  hasActivities: boolean;
  /** Every week slot, in order. When given, the dialog also offers the whole session. */
  weeks?: WeekInfo[];
  /** How long the session is: it comes from the session picked at the top of the page. */
  sessionWeeks?: SessionWeeks;
  /** The session by name, for the heading. */
  sessionName?: string;
  onCancel: () => void;
  onGenerate: (plan: AutoGeneratePlan) => void;
}

const defaultChoice = (w: WeekInfo): WeekChoice => (w.built ? 'lock' : w.hasActivities ? 'fill-empty' : 'replace-all');

/** Confirm dialog for Auto generate: one week or the whole session, what to do with what is already there, and which session it is. */
export default function AutoGenerateDialog({ weekNumber, hasActivities, weeks = [], sessionWeeks = 4, sessionName, onCancel, onGenerate }: Props) {
  const [scope, setScope] = useState<'week' | 'session'>('week');
  const [mode, setMode] = useState<AutoGenerateMode>('fill-empty');
  const [keepTrips, setKeepTrips] = useState(true);
  const [useOtherWeeks, setUseOtherWeeks] = useState(true);
  const [keepPast, setKeepPast] = useState(true);
  const [choices, setChoices] = useState<WeekChoice[]>(() => weeks.map(defaultChoice));

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onCancel();
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [onCancel]);

  const inSession = weeks.slice(0, sessionWeeks);
  const sessionPlan = inSession.map((_, index) => ({ index, choice: choices[index] })).filter((w) => w.choice !== 'lock');
  const replacing = scope === 'week' ? mode === 'replace-all' && hasActivities : sessionPlan.some((w) => w.choice === 'replace-all' && inSession[w.index].hasActivities);
  const nothingToDo = scope === 'session' && sessionPlan.length === 0;

  const generate = () => {
    const list =
      scope === 'week'
        ? [{ index: weekNumber - 1, mode: hasActivities ? mode : ('replace-all' as AutoGenerateMode) }]
        : sessionPlan.map((w) => ({ index: w.index, mode: w.choice as AutoGenerateMode }));
    onGenerate({ sessionWeeks, keepTrips, useOtherWeeks, keepPast, weeks: list });
  };

  const title = scope === 'week' ? `Auto generate Week ${weekNumber}?` : 'Auto generate the session?';
  return (
    <div className="modal-backdrop" onMouseDown={(e) => e.target === e.currentTarget && onCancel()}>
      <div className="modal" role="dialog" aria-modal="true" aria-labelledby="autogen-title">
        <h2 id="autogen-title">{title}</h2>
        <p className="hint">
          A week usually takes a few seconds. One that will not come out is given 45 seconds at the most, and then comes back with the
          periods it could not settle left empty and marked yellow for you to fill, so what you get always keeps the rules.
        </p>
        <p>
          This builds the periods from the bunks on the Build tab. The session calendar (trips, Tiyuls, village day and the rest,
          on the Settings tab) goes on first where it is not there yet, and the periods are built around it and around anything
          you have entered by hand. It reads the other weeks you have loaded, so each bunk&apos;s totals stay fair across the whole
          session. Every time you run it you get a different valid schedule, so you can keep regenerating until you like one.
        </p>

        {weeks.length > 0 && (
          <fieldset>
            <legend>What should be generated?</legend>
            <label>
              <input type="radio" name="autogen-scope" checked={scope === 'week'} onChange={() => setScope('week')} /> Just Week {weekNumber}
            </label>
            <label>
              <input type="radio" name="autogen-scope" checked={scope === 'session'} onChange={() => setScope('session')} /> The whole
              session, week by week
            </label>
          </fieldset>
        )}

        {scope === 'week' && hasActivities && (
          <fieldset>
            <legend>Week {weekNumber} already has activities in it. What should happen to them?</legend>
            <label>
              <input type="radio" name="autogen-mode" checked={mode === 'fill-empty'} onChange={() => setMode('fill-empty')} /> Keep what
              is there and build around it. Only the empty periods are filled.
            </label>
            <label>
              <input type="radio" name="autogen-mode" checked={mode === 'replace-all'} onChange={() => setMode('replace-all')} /> Replace
              what is there. Week {weekNumber} is cleared first.
            </label>
          </fieldset>
        )}

        {scope === 'session' && (
          <fieldset>
            <legend>What should happen to each week?</legend>
            {inSession.map((w, index) => (
              <label key={index}>
                Week {index + 1}{' '}
                <select
                  value={choices[index]}
                  onChange={(e) => setChoices((list) => list.map((c, i) => (i === index ? (e.target.value as WeekChoice) : c)))}
                >
                  <option value="lock">Lock: leave it exactly as it is</option>
                  <option value="fill-empty">Build around what is there</option>
                  <option value="replace-all">Regenerate: clear it and build it again</option>
                </select>
                {!w.hasBunks && choices[index] !== 'lock' && <span className="muted"> uses Week {weekNumber}&apos;s bunks</span>}
              </label>
            ))}
          </fieldset>
        )}

        <fieldset>
          <legend>Options</legend>
          <label>
            <input type="checkbox" checked={keepTrips} disabled={!replacing} onChange={(e) => setKeepTrips(e.target.checked)} /> When
            replacing, keep Bike Trip and Tiyul where they are.
          </label>
          <label>
            <input type="checkbox" checked={useOtherWeeks} onChange={(e) => setUseOtherWeeks(e.target.checked)} /> Count what the other
            weeks already have.
          </label>
          <label>
            <input type="checkbox" checked={keepPast} onChange={(e) => setKeepPast(e.target.checked)} /> Leave the days that have already
            happened as they are (through today).
          </label>
          <p className="hint">
            Ticked: a bunk that already had Yoga twice in a week you are keeping will not be given a third, and its visit numbers carry on
            from there. Unticked: the weeks you are not generating are ignored, as if this were the only schedule.
          </p>
        </fieldset>

        {sessionName && <p className="muted">{sessionName}. To change it, pick the other session at the top of the page.</p>}

        <div className="modal-buttons">
          <button type="button" onClick={onCancel}>
            Cancel
          </button>{' '}
          <button type="button" className="primary" autoFocus disabled={nothingToDo} onClick={generate}>
            Generate
          </button>
        </div>
      </div>
    </div>
  );
}
