import { useCallback, useEffect, useRef, useState, type ChangeEvent } from 'react';
import AutoGenerateDialog, { type AutoGeneratePlan, type WeekInfo } from './components/AutoGenerateDialog';
import AutoGenerateStatus from './components/AutoGenerateStatus';
import BuildGrid from './components/BuildGrid';
// import DayDetails from './components/DayDetails';
import ScheduleView from './components/ScheduleView';
import TrackingView from './components/TrackingView';
import { bunkIdsForLabel, slotsForLabel, villageOf } from './autofill';
import { APP_MAX_MS, BUILT_WEEK_MAX_EMPTY } from './autogen/config';
import { isBuiltWeek } from './autogen/history';
import { generateWeekAsync } from './autogen';
import { applyClear, countToClear, dropMarks, pruneCleared, type ClearRequest } from './clear';
import { WEEK_COUNT } from './config';
import { downloadAllWeeks, downloadWeek, readUploadedFile } from './excel';
import { emptySchedule, newBunk, sampleSchedule } from './sample';
import { defaultWeeksState, loadWeeks, saveWeeks } from './storage';
import type { Schedule, WeeksState } from './types';
// import type { DayInfo } from './types';

type View = 'build' | 'schedule' | 'tracking';

const TABS: { id: View; label: string }[] = [
  { id: 'build', label: 'Build' },
  { id: 'schedule', label: 'Schedule' },
  { id: 'tracking', label: 'Tracking' },
];

const weekLabel = (index: number): string => `Week ${index + 1}`;
const isEmpty = (s: Schedule | null): boolean => !s || s.bunks.length === 0;
/** A period that has been filled again loses its yellow "cleared" mark. */
const withoutFilledMarks = (s: Schedule): Schedule => ({ ...s, bunks: s.bunks.map(pruneCleared) });

export default function App() {
  const [weeksState, setWeeksState] = useState<WeeksState>(() => loadWeeks() ?? defaultWeeksState());
  const [view, setView] = useState<View>('build');
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [autoOpen, setAutoOpen] = useState(false);
  /** What the last Auto generate did, kept in memory only so it can be undone. */
  const [auto, setAuto] = useState<{ weeks: number[]; seed: number; before: (Schedule | null)[] } | null>(null);
  /** Text on the button while a run is going, or null when idle. */
  const [generating, setGenerating] = useState<string | null>(null);
  const abortRef = useRef<AbortController | null>(null);

  useEffect(() => saveWeeks(weeksState), [weeksState]);

  const current = weeksState.current;
  const schedule = weeksState.weeks[current] ?? emptySchedule();
  const allSchedules = weeksState.weeks.filter((w): w is Schedule => w !== null);
  const previousWeek = current > 0 ? weeksState.weeks[current - 1] : null;

  const updateCurrentSchedule = useCallback((fn: (s: Schedule) => Schedule) => {
    setAuto(null); // a manual edit ends the chance to undo the last Auto generate
    setWeeksState((ws) => ({
      ...ws,
      weeks: ws.weeks.map((w, i) => (i === ws.current ? withoutFilledMarks(fn(w ?? emptySchedule())) : w)),
    }));
  }, []);

  const switchWeek = useCallback((index: number) => {
    // looking at another week keeps the chance to undo: a whole-session run touches several weeks
    setWeeksState((ws) => ({
      current: index,
      weeks: ws.weeks[index] === null ? ws.weeks.map((w, i) => (i === index ? emptySchedule() : w)) : ws.weeks,
    }));
  }, []);

  // Hobbies is always the whole camp, and a league is always the clicked bunk's whole village,
  // both for their natural double/single period. A later edit to just one cell is a manual
  // exception and only ever touches that one bunk/period, never cascading.
  const setCell = useCallback(
    (bunkId: string, slot: number, label: string) => {
      updateCurrentSchedule((s) => {
        if (!label) {
          return { ...s, bunks: s.bunks.map((b) => (b.id === bunkId ? { ...b, slots: b.slots.map((v, i) => (i === slot ? label : v)) } : b)) };
        }
        const targetBunkIds = bunkIdsForLabel(label, bunkId, s.bunks);
        const targetSlots = slotsForLabel(label, slot);
        return {
          ...s,
          bunks: s.bunks.map((b) =>
            targetBunkIds.has(b.id) ? { ...b, slots: b.slots.map((v, i) => (targetSlots.includes(i) ? label : v)) } : b,
          ),
        };
      });
    },
    [updateCurrentSchedule],
  );

  const fillSlots = useCallback(
    (slots: number[], label: string, village: string | null) => {
      updateCurrentSchedule((s) => ({
        ...s,
        bunks: s.bunks.map((b) =>
          !village || villageOf(b.name) === village
            ? { ...b, slots: b.slots.map((v, i) => (slots.includes(i) ? label : v)) }
            : b,
        ),
      }));
    },
    [updateCurrentSchedule],
  );

  // The Clear tool: empty a program area, a bunk, a village or everyone for a day (or the week), and leave the
  // emptied periods marked in yellow so it is plain what still has to be filled.
  const clearPeriods = useCallback(
    (req: ClearRequest, description: string) => {
      const n = countToClear(schedule.bunks, req);
      if (n === 0) {
        window.alert(`Nothing to clear: ${description} has nothing there.`);
        return;
      }
      if (!window.confirm(`Clear ${description}? ${n} period${n === 1 ? '' : 's'} will be left empty and marked in yellow.`)) return;
      updateCurrentSchedule((s) => ({ ...s, bunks: applyClear(s.bunks, req) }));
    },
    [schedule.bunks, updateCurrentSchedule],
  );

  const removeMarks = useCallback(() => {
    updateCurrentSchedule((s) => ({ ...s, bunks: dropMarks(s.bunks) }));
  }, [updateCurrentSchedule]);

  const setBunkField = useCallback(
    (id: string, field: 'name' | 'grades' | 'count', value: string) => {
      updateCurrentSchedule((s) => ({ ...s, bunks: s.bunks.map((b) => (b.id === id ? { ...b, [field]: value } : b)) }));
    },
    [updateCurrentSchedule],
  );

  const addBunk = useCallback(() => {
    updateCurrentSchedule((s) => ({ ...s, bunks: [...s.bunks, newBunk()] }));
  }, [updateCurrentSchedule]);

  const removeBunk = useCallback(
    (id: string) => {
      updateCurrentSchedule((s) => ({ ...s, bunks: s.bunks.filter((b) => b.id !== id) }));
    },
    [updateCurrentSchedule],
  );

  const moveBunk = useCallback(
    (id: string, direction: -1 | 1) => {
      updateCurrentSchedule((s) => {
        const i = s.bunks.findIndex((b) => b.id === id);
        const j = i + direction;
        if (i < 0 || j < 0 || j >= s.bunks.length) return s;
        const bunks = [...s.bunks];
        [bunks[i], bunks[j]] = [bunks[j], bunks[i]];
        return { ...s, bunks };
      });
    },
    [updateCurrentSchedule],
  );

  // const setDayField = useCallback((index: number, field: keyof DayInfo, value: string) => {
  //   updateCurrentSchedule((s) => ({ ...s, days: s.days.map((d, i) => (i === index ? { ...d, [field]: value } : d)) }));
  // }, [updateCurrentSchedule]);

  const resetToSample = () => {
    if (window.confirm(`Replace ${weekLabel(current)} with the sample schedule?`)) updateCurrentSchedule(() => sampleSchedule());
  };

  const clearActivities = () => {
    if (window.confirm('Clear every activity? Bunks stay.')) {
      updateCurrentSchedule((s) => ({ ...s, bunks: s.bunks.map((b) => ({ ...b, slots: b.slots.map(() => '') })) }));
    }
  };

  const resetWeek = () => {
    if (window.confirm(`Reset ${weekLabel(current)}? This clears all bunks and activities for this week.`)) {
      updateCurrentSchedule(() => emptySchedule());
    }
  };

  const useLastWeekBunks = () => {
    if (!previousWeek || previousWeek.bunks.length === 0) return;
    const msg =
      schedule.bunks.length > 0
        ? `Replace ${weekLabel(current)}'s bunks with ${weekLabel(current - 1)}'s roster? Activities already set for this week will be cleared.`
        : `Fill ${weekLabel(current)} with ${weekLabel(current - 1)}'s bunk roster (names, grades, counts, empty activities)?`;
    if (!window.confirm(msg)) return;
    updateCurrentSchedule((s) => ({
      ...s,
      bunks: previousWeek.bunks.map((b) => newBunk(b.name, b.grades, b.count)),
    }));
  };

  const hasActivities = schedule.bunks.some((b) => b.slots.some((l) => l !== ''));

  const weekInfo: WeekInfo[] = weeksState.weeks.map((w) => ({
    hasBunks: !isEmpty(w),
    hasActivities: !!w && w.bunks.some((b) => b.slots.some((l) => l !== '')),
    built: isBuiltWeek(w, BUILT_WEEK_MAX_EMPTY),
  }));

  const runAutoGenerate = async (plan: AutoGeneratePlan) => {
    setAutoOpen(false);
    const abort = new AbortController();
    abortRef.current = abort;
    const before = weeksState.weeks;
    const roster = schedule.bunks;
    const seed = Math.floor(Math.random() * 2 ** 31);
    const generated = new Set(plan.weeks.map((w) => w.index));
    // a working copy: each week is generated in turn and reads the ones done before it
    const working = [...before];
    try {
      for (const [n, { index, mode }] of plan.weeks.entries()) {
        setGenerating(plan.weeks.length > 1 ? `Generating ${weekLabel(index)} (${n + 1} of ${plan.weeks.length})...` : 'Generating...');
        await new Promise<void>((resolve) => setTimeout(resolve, 0)); // let the button show it first
        // a week with no bunks yet takes the bunks of the week on screen
        if (isEmpty(working[index])) working[index] = { ...emptySchedule(), bunks: roster.map((b) => newBunk(b.name, b.grades, b.count)) };
        // starting fresh: the weeks that are not part of this run are hidden from the generator
        const visible = plan.useOtherWeeks ? working : working.map((w, i) => (generated.has(i) ? w : null));
        const result = await generateWeekAsync({
          weeks: { current: index, weeks: visible },
          weekIndex: index + 1,
          mode,
          sessionWeeks: plan.sessionWeeks,
          seed: (seed + n * 7919) | 0,
          keepTrips: plan.keepTrips,
          signal: abort.signal,
          maxMs: APP_MAX_MS,
        });
        if (!result) return; // cancelled: nothing is changed
        // Nothing about shortfalls is ever shown; this is only for whoever has the console open.
        console.debug('Auto generate', {
          week: index + 1,
          seed,
          rounds: result.rounds,
          hard: result.quality.hard.length,
          major: result.quality.major.length,
          minor: result.quality.minor.length,
          warnings: result.warnings,
        });
        working[index] = withoutFilledMarks(result.schedule);
      }
      setAuto({ weeks: plan.weeks.map((w) => w.index), seed, before });
      setWeeksState((ws) => ({ ...ws, weeks: working }));
    } finally {
      abortRef.current = null;
      setGenerating(null);
    }
  };

  const undoAutoGenerate = () => {
    if (!auto) return;
    setWeeksState((ws) => ({ ...ws, weeks: auto.before }));
    setAuto(null);
  };

  const handleDownload = () => downloadWeek(schedule, current + 1);
  const handleDownloadAll = () => downloadAllWeeks(weeksState.weeks);

  const handleUploadClick = () => fileInputRef.current?.click();

  const handleFileChange = async (e: ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    e.target.value = '';
    if (!file) return;

    const parsed = await readUploadedFile(file);
    if (parsed.length === 0) {
      window.alert("Couldn't read that file. Upload something downloaded from this app.");
      return;
    }

    const inRange = parsed.filter((p) => p.weekNumber >= 1 && p.weekNumber <= WEEK_COUNT);
    const overflow = parsed.length - inRange.length;
    const overflowNote = overflow > 0 ? ` ${overflow} week(s) beyond ${weekLabel(WEEK_COUNT - 1)} in the file were skipped.` : '';
    if (inRange.length === 0) {
      window.alert(`Nothing to load.${overflowNote}`);
      return;
    }

    const summary = inRange
      .map((p) => `${weekLabel(p.weekNumber - 1)}${isEmpty(weeksState.weeks[p.weekNumber - 1]) ? '' : ' (overwrite)'}`)
      .join(', ');
    if (!window.confirm(`Load ${summary}?${overflowNote}`)) return;

    setAuto(null);
    setWeeksState((ws) => {
      const weeks = [...ws.weeks];
      for (const p of inRange) weeks[p.weekNumber - 1] = p.schedule;
      return { weeks, current: inRange[0].weekNumber - 1 };
    });
  };

  return (
    <div>
      <header>
        <h1>Weekly Period Schedule Builder</h1>
        <p>Build a sample week: four periods a day, Sunday to Friday. Your work is saved in this browser.</p>
        <nav>
          {TABS.map((t) => (
            <button key={t.id} type="button" aria-pressed={view === t.id} onClick={() => setView(t.id)}>
              {t.label}
            </button>
          ))}
        </nav>
      </header>

      <main>
        <div className="weekbar">
          <label>
            Week:{' '}
            <select value={current} onChange={(e) => switchWeek(Number(e.target.value))}>
              {Array.from({ length: WEEK_COUNT }, (_, i) => (
                <option key={i} value={i}>
                  {weekLabel(i)}
                  {isEmpty(weeksState.weeks[i]) ? ' (empty)' : ''}
                </option>
              ))}
            </select>
          </label>{' '}
          <button type="button" onClick={handleDownload}>
            Download {weekLabel(current)} (.xlsx)
          </button>{' '}
          <button type="button" onClick={handleDownloadAll}>
            Download all weeks (.xlsx)
          </button>{' '}
          <button type="button" onClick={handleUploadClick}>
            Upload
          </button>
          <input ref={fileInputRef} type="file" accept=".xlsx" hidden onChange={handleFileChange} />
          {' '}
          <button type="button" onClick={resetWeek}>
            Reset {weekLabel(current)}
          </button>{' '}
          <button
            type="button"
            onClick={() => setAutoOpen(true)}
            disabled={schedule.bunks.length === 0 || generating !== null}
            title={schedule.bunks.length === 0 ? 'Add bunks on the Build tab first.' : undefined}
          >
            {generating !== null && <span className="spinner" aria-hidden="true" />}
            {generating ?? `Auto generate ${weekLabel(current)}`}
          </button>
          {generating !== null && (
            <>
              {' '}
              <button type="button" onClick={() => abortRef.current?.abort()}>
                Cancel
              </button>
            </>
          )}
          {auto && <AutoGenerateStatus weekNumbers={auto.weeks.map((w) => w + 1)} seed={auto.seed} onUndo={undoAutoGenerate} />}
        </div>

        {autoOpen && (
          <AutoGenerateDialog
            weekNumber={current + 1}
            hasActivities={hasActivities}
            weeks={weekInfo}
            onCancel={() => setAutoOpen(false)}
            onGenerate={runAutoGenerate}
          />
        )}

        {view === 'build' && (
          <>
            <BuildGrid
              bunks={schedule.bunks}
              onCell={setCell}
              onBunk={setBunkField}
              onAdd={addBunk}
              onRemove={removeBunk}
              onMove={moveBunk}
              onFillSlots={fillSlots}
              onClear={clearPeriods}
              onRemoveMarks={removeMarks}
              usePreviousWeek={
                current > 0
                  ? {
                      label: `Use ${weekLabel(current - 1)}'s bunks`,
                      disabled: !previousWeek || previousWeek.bunks.length === 0,
                      onClick: useLastWeekBunks,
                    }
                  : undefined
              }
            />
            {/* <DayDetails days={schedule.days} onDay={setDayField} /> */}
          </>
        )}
        {view === 'schedule' && <ScheduleView bunks={schedule.bunks} days={schedule.days} />}
        {view === 'tracking' && <TrackingView bunks={schedule.bunks} weekLabel={weekLabel(current)} schedules={allSchedules} />}
      </main>

      <footer>
        <button type="button" onClick={clearActivities}>
          Clear all activities
        </button>{' '}
        <button type="button" onClick={resetToSample}>
          Reset to sample
        </button>
      </footer>
    </div>
  );
}
