import { useCallback, useEffect, useMemo, useRef, useState, type ChangeEvent } from 'react';
import AutoGenerateDialog, { type AutoGeneratePlan, type WeekInfo } from './components/AutoGenerateDialog';
import AutoGenerateProgress, { type RunProgress } from './components/AutoGenerateProgress';
import AutoGenerateStatus from './components/AutoGenerateStatus';
import BuildGrid from './components/BuildGrid';
import HelpPanel from './components/HelpPanel';
// import DayDetails from './components/DayDetails';
import ScheduleView from './components/ScheduleView';
import SettingsView from './components/SettingsView';
import SpecialistView from './components/SpecialistView';
import TrackingView from './components/TrackingView';
import { bunkIdsForLabel, slotsForLabel, villageName, villageOf } from './autofill';
import { BUILT_WEEK_MAX_EMPTY } from './autogen/config';
import { isBuiltWeek } from './autogen/history';
import { startRun } from './autogen/background';
import { checkSettings } from './autogen/feasibility';
import { applySettings, bigVillageIn, isDefaultSettings, normalizeSettings, templateSettings, usesBigVillageSettings, withBigVillageSettings, type Settings } from './autogen/settings';
import { applyClear, countToClear, dropMarks, pruneCleared, type ClearRequest } from './clear';
import { APP_VERSION, SUPPORT_LINK } from './config';
import { downloadAllWeeks, downloadSpecialists, downloadWeek, readUploadedFile } from './excel';
import { emptySchedule, newBunk, sampleSchedule } from './sample';
import { MAX_BUNKS_IN_CAMP, MAX_CAMPERS_PER_BUNK, addableVillages, biggestCampSize, datesOf, dayLabels, pastDaysOf, startSession, withBiggestCamp, withBunkAdded, templateOf, weekDates, withCalendar, type SessionId } from './session';
import { SESSION_TEMPLATES, calendarFor } from './autogen/sessionCalendar';
import { isFirstVisit, loadSession, loadWeeks, markHelpSeen, saveSession, saveWeeks } from './storage';
import type { Schedule, WeeksState } from './types';
// import type { DayInfo } from './types';

type View = 'build' | 'schedule' | 'tracking' | 'specialists' | 'settings';

const TABS: { id: View; label: string }[] = [
  { id: 'build', label: 'Build' },
  { id: 'schedule', label: 'Schedule' },
  { id: 'tracking', label: 'Tracking' },
  { id: 'specialists', label: 'Specialists' },
  { id: 'settings', label: 'Settings' },
];

const weekLabel = (index: number): string => `Week ${index + 1}`;
const isEmpty = (s: Schedule | null): boolean => !s || s.bunks.length === 0;
/** A period that has been filled again loses its yellow "cleared" mark. */
const withoutFilledMarks = (s: Schedule): Schedule => ({ ...s, bunks: s.bunks.map(pruneCleared) });

export default function App() {
  const [weeksState, setWeeksState] = useState<WeeksState>(() => loadWeeks() ?? startSession(SESSION_TEMPLATES[0]));
  const [view, setView] = useState<View>('build');
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [autoOpen, setAutoOpen] = useState(false);
  // the how-to opens by itself the very first time the page is opened in this browser, and only then
  const [helpOpen, setHelpOpen] = useState(isFirstVisit);
  useEffect(() => {
    if (helpOpen) markHelpSeen();
  }, [helpOpen]);
  /** What the last Auto generate did, kept in memory only so it can be undone. */
  const [auto, setAuto] = useState<{ weeks: number[]; seed: number; before: (Schedule | null)[] } | null>(null);
  /** The Auto generate run that is going on in the background, or null when idle. `indexes` are its 0-based weeks. */
  const [run, setRun] = useState<(RunProgress & { indexes: number[] }) | null>(null);
  const runRef = useRef<{ stop: () => void } | null>(null);

  useEffect(() => saveWeeks(weeksState), [weeksState]);
  useEffect(() => () => runRef.current?.stop(), []);

  // which session this is: it decides how many weeks there are, the dates, the calendar and the numbers it starts from
  const template = templateOf(weeksState.session);
  const WEEK_COUNT = template.weeks;
  // the generator and the rule checker read their numbers from one place: keep it in step with this schedule's settings
  const settings = useMemo(() => {
    const mine = normalizeSettings(weeksState.settings ?? templateSettings(template));
    applySettings(mine);
    return mine;
  }, [weeksState.settings, template]);
  const setSettings = useCallback((next: Settings | null) => {
    setWeeksState((ws) => {
      const { settings: _old, ...rest } = ws;
      // what is kept is what differs from the app's own numbers; nothing kept means the session's own
      const mine = normalizeSettings(next ?? templateSettings(templateOf(ws.session)));
      return isDefaultSettings(mine) ? rest : { ...rest, settings: mine };
    });
  }, []);

  /** Go to the other session. Each keeps its own schedule, bunks and settings; one that has never been opened starts from its template. */
  const switchSession = (id: SessionId) => {
    if (id === template.id || run !== null) return;
    saveSession(template.id, { ...weeksState, session: template.id });
    setAuto(null);
    setWeeksState(loadSession(id) ?? startSession(templateOf(id)));
  };
  /** Throw this session's schedule away and start it again from its template. */
  const startOver = () => {
    if (!window.confirm(`Start ${template.name} over? Its bunks, its schedule and its settings go back to the way the session starts. This cannot be undone.`)) return;
    setAuto(null);
    setWeeksState(startSession(template));
  };
  // Setting up: a bunk added with one click goes into every week of the session, and the biggest camp can be filled in at once
  const addBunkTo = (village: string) => {
    if (withBunkAdded(weeksState, village) === weeksState) {
      window.alert(`The camp has ${MAX_BUNKS_IN_CAMP} cabins, and a week of this session already has that many bunks. Remove one first.`);
      return;
    }
    setAuto(null);
    setWeeksState((ws) => withBunkAdded(ws, village));
  };
  const fillBiggestCamp = () => {
    if (!window.confirm(`Fill in the biggest camp for ${template.name}? Every village goes up to its most bunks in every week, and every bunk is set to ${MAX_CAMPERS_PER_BUNK} campers. Bunks that are already there stay, with everything on their rows.`)) return;
    setAuto(null);
    setWeeksState((ws) => withBiggestCamp(ws));
  };
  const putCalendarOn = () => {
    setAuto(null);
    setWeeksState((ws) => withCalendar(ws));
    setView('build');
  };

  const current = weeksState.current;
  /** A week that is part of the run can be looked at, not changed, until the run is over. */
  const locked = !!run?.indexes.includes(current);
  const schedule = weeksState.weeks[current] ?? emptySchedule();
  const allSchedules = weeksState.weeks.filter((w): w is Schedule => w !== null);
  const previousWeek = current > 0 ? weeksState.weeks[current - 1] : null;

  const updateCurrentSchedule = useCallback((fn: (s: Schedule) => Schedule) => {
    setAuto(null); // a manual edit ends the chance to undo the last Auto generate
    setWeeksState((ws) => ({
      ...ws,
      weeks: ws.weeks.map((w, i) => (i === ws.current ? withoutFilledMarks(fn(w ?? emptySchedule())) : w)),
    }));
  }, []);

  const switchWeek = useCallback((index: number) => {
    // looking at another week keeps the chance to undo: a whole-session run touches several weeks
    setWeeksState((ws) => ({
      ...ws,
      current: index,
      weeks: ws.weeks[index] === null ? ws.weeks.map((w, i) => (i === index ? emptySchedule() : w)) : ws.weeks,
    }));
  }, []);

  // Hobbies is always the whole camp, and a league is always the clicked bunk's whole village,
  // both for their natural double/single period. A later edit to just one cell is a manual
  // exception and only ever touches that one bunk/period, never cascading.
  const setCell = useCallback(
    (bunkId: string, slot: number, label: string) => {
      updateCurrentSchedule((s) => {
        if (!label) {
          return { ...s, bunks: s.bunks.map((b) => (b.id === bunkId ? { ...b, slots: b.slots.map((v, i) => (i === slot ? label : v)) } : b)) };
        }
        const targetBunkIds = bunkIdsForLabel(label, bunkId, s.bunks);
        const targetSlots = slotsForLabel(label, slot);
        return {
          ...s,
          bunks: s.bunks.map((b) =>
            targetBunkIds.has(b.id) ? { ...b, slots: b.slots.map((v, i) => (targetSlots.includes(i) ? label : v)) } : b,
          ),
        };
      });
    },
    [updateCurrentSchedule],
  );

  const fillSlots = useCallback(
    (slots: number[], label: string, village: string | null) => {
      updateCurrentSchedule((s) => ({
        ...s,
        bunks: s.bunks.map((b) =>
          !village || villageOf(b.name) === village
            ? { ...b, slots: b.slots.map((v, i) => (slots.includes(i) ? label : v)) }
            : b,
        ),
      }));
    },
    [updateCurrentSchedule],
  );

  // The Clear tool: empty a program area, a bunk, a village or everyone for a day (or the week), and leave the
  // emptied periods marked in yellow so it is plain what still has to be filled.
  const clearPeriods = useCallback(
    (req: ClearRequest, description: string) => {
      const n = countToClear(schedule.bunks, req);
      if (n === 0) {
        window.alert(`Nothing to clear: ${description} has nothing there.`);
        return;
      }
      if (!window.confirm(`Clear ${description}? ${n} period${n === 1 ? '' : 's'} will be left empty and marked in yellow.`)) return;
      updateCurrentSchedule((s) => ({ ...s, bunks: applyClear(s.bunks, req) }));
    },
    [schedule.bunks, updateCurrentSchedule],
  );

  const removeMarks = useCallback(() => {
    updateCurrentSchedule((s) => ({ ...s, bunks: dropMarks(s.bunks) }));
  }, [updateCurrentSchedule]);

  const setBunkField = useCallback(
    (id: string, field: 'name' | 'grades' | 'count', value: string) => {
      updateCurrentSchedule((s) => ({ ...s, bunks: s.bunks.map((b) => (b.id === id ? { ...b, [field]: value } : b)) }));
    },
    [updateCurrentSchedule],
  );

  const addBunk = useCallback(() => {
    updateCurrentSchedule((s) => ({ ...s, bunks: [...s.bunks, newBunk()] }));
  }, [updateCurrentSchedule]);

  const removeBunk = useCallback(
    (id: string) => {
      updateCurrentSchedule((s) => ({ ...s, bunks: s.bunks.filter((b) => b.id !== id) }));
    },
    [updateCurrentSchedule],
  );

  const moveBunk = useCallback(
    (id: string, direction: -1 | 1) => {
      updateCurrentSchedule((s) => {
        const i = s.bunks.findIndex((b) => b.id === id);
        const j = i + direction;
        if (i < 0 || j < 0 || j >= s.bunks.length) return s;
        const bunks = [...s.bunks];
        [bunks[i], bunks[j]] = [bunks[j], bunks[i]];
        return { ...s, bunks };
      });
    },
    [updateCurrentSchedule],
  );

  // const setDayField = useCallback((index: number, field: keyof DayInfo, value: string) => {
  //   updateCurrentSchedule((s) => ({ ...s, days: s.days.map((d, i) => (i === index ? { ...d, [field]: value } : d)) }));
  // }, [updateCurrentSchedule]);

  const resetToSample = () => {
    if (window.confirm(`Replace ${weekLabel(current)} with the sample schedule?`)) updateCurrentSchedule(() => sampleSchedule());
  };

  const clearActivities = () => {
    if (window.confirm('Clear every activity? Bunks stay.')) {
      updateCurrentSchedule((s) => ({ ...s, bunks: s.bunks.map((b) => ({ ...b, slots: b.slots.map(() => '') })) }));
    }
  };

  const resetWeek = () => {
    if (window.confirm(`Reset ${weekLabel(current)}? This clears all bunks and activities for this week.`)) {
      updateCurrentSchedule(() => emptySchedule());
    }
  };

  const useLastWeekBunks = () => {
    if (!previousWeek || previousWeek.bunks.length === 0) return;
    const msg =
      schedule.bunks.length > 0
        ? `Replace ${weekLabel(current)}'s bunks with ${weekLabel(current - 1)}'s roster? Activities already set for this week will be cleared.`
        : `Fill ${weekLabel(current)} with ${weekLabel(current - 1)}'s bunk roster (names, grades, counts, empty activities)?`;
    if (!window.confirm(msg)) return;
    updateCurrentSchedule((s) => ({
      ...s,
      bunks: previousWeek.bunks.map((b) => newBunk(b.name, b.grades, b.count)),
    }));
  };

  const hasActivities = schedule.bunks.some((b) => b.slots.some((l) => l !== ''));

  const weekInfo: WeekInfo[] = weeksState.weeks.map((w) => ({
    hasBunks: !isEmpty(w),
    hasActivities: !!w && w.bunks.some((b) => b.slots.some((l) => l !== '')),
    built: isBuiltWeek(w, BUILT_WEEK_MAX_EMPTY),
  }));

  // The run works in the background, one week after another, each reading the ones done before it. A week that does not
  // come out good is thrown away and generated again (and the week before it too, if it keeps failing), so only good weeks
  // are handed over. Each week is put on the page as soon as it is done, while the later ones are still being worked on.
  const runAutoGenerate = (plan: AutoGeneratePlan) => {
    setAutoOpen(false);
    setAuto(null);
    const before = weeksState.weeks;
    const indexes = plan.weeks.map((w) => w.index);
    const seed = Math.floor(Math.random() * 2 ** 31);
    const handedOver = new Set<number>();
    const end = () => {
      runRef.current = null;
      setRun(null);
      if (handedOver.size > 0) setAuto({ weeks: indexes.filter((i) => handedOver.has(i)), seed, before });
    };
    setRun({ indexes, weekNumbers: indexes.map((i) => i + 1), states: indexes.map(() => 'waiting'), tries: 0, startedAt: Date.now() });
    // a camp with six bunks in a village is switched to the settings that fit it, when the dialog was left saying so
    const using = plan.useBigVillageSettings ? withBigVillageSettings(settings) : settings;
    if (plan.useBigVillageSettings) setSettings(using);
    const started = startRun(
      {
        weeks: before,
        // days that have already happened stay as they are, when that is asked for
        steps: plan.weeks.map((w) => ({ ...w, pastDays: plan.keepPast ? pastDaysOf(template, w.index + 1) : 0 })),
        roster: schedule.bunks, // a week with no bunks yet takes the bunks of the week on screen
        sessionWeeks: template.weeks,
        keepTrips: plan.keepTrips,
        useOtherWeeks: plan.useOtherWeeks,
        seed,
        settings: using,
        // the session calendar goes down first: opening day, trips, village day, Mass Program or Color War, Taste of CSL
        calendar: true,
      },
      {
        // a step lower than the last one means that week is being redone: it and the ones after it are not done any more
        onProgress: (step, tries) =>
          setRun((r) => r && { ...r, tries, states: r.states.map((s, i) => (i < step ? s : i === step ? 'working' : 'waiting')) }),
        onWeek: (step, done) => {
          handedOver.add(indexes[step]);
          setWeeksState((ws) => ({ ...ws, weeks: ws.weeks.map((w, i) => (i === indexes[step] ? withoutFilledMarks(done) : w)) }));
          setRun((r) => r && { ...r, states: r.states.map((s, i) => (i === step ? 'done' : s)) });
        },
        onDone: (result) => {
          // Nothing about shortfalls is ever shown; this is only for whoever has the console open.
          console.debug('Auto generate', {
            seed,
            good: result?.good,
            tries: result?.tries,
            weeks: result?.results.map((r, n) => ({ week: indexes[n] + 1, rounds: r.rounds, hard: r.quality.hard, major: r.quality.major, minor: r.quality.minor.length })),
          });
          end();
        },
      },
    );
    runRef.current = { stop: () => (started.stop(), end()) };
  };

  // Undo puts back the weeks the run made, and leaves alone anything changed in other weeks since.
  const undoAutoGenerate = () => {
    if (!auto) return;
    setWeeksState((ws) => ({ ...ws, weeks: ws.weeks.map((w, i) => (auto.weeks.includes(i) ? auto.before[i] : w)) }));
    setAuto(null);
  };

  const handleDownload = () => downloadWeek(schedule, current + 1, settings, template.id);
  const handleDownloadAll = () => downloadAllWeeks(weeksState.weeks, settings, template.id);

  const handleUploadClick = () => fileInputRef.current?.click();

  const handleFileChange = async (e: ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    e.target.value = '';
    if (!file) return;

    const { weeks: parsed, settings: uploaded, session: fileSession } = await readUploadedFile(file);
    if (parsed.length === 0) {
      window.alert("Couldn't read that file. Upload something downloaded from this app.");
      return;
    }

    const inRange = parsed.filter((p) => p.weekNumber >= 1 && p.weekNumber <= WEEK_COUNT);
    const overflow = parsed.length - inRange.length;
    const overflowNote = overflow > 0 ? ` ${overflow} week(s) beyond ${weekLabel(WEEK_COUNT - 1)} in the file were skipped.` : '';
    if (inRange.length === 0) {
      window.alert(`Nothing to load.${overflowNote}`);
      return;
    }

    const summary = inRange
      .map((p) => `${weekLabel(p.weekNumber - 1)}${isEmpty(weeksState.weeks[p.weekNumber - 1]) ? '' : ' (overwrite)'}`)
      .join(', ');
    const settingsNote = uploaded && !isDefaultSettings(uploaded) ? ' The file also carries its own settings, which will replace the ones here.' : '';
    // a file saved from the other session is loaded into that session, and this one is put away as it is
    const other = fileSession && fileSession !== template.id ? templateOf(fileSession) : null;
    const sessionNote = other ? ` The file is from ${other.name}: it will be loaded there, and ${template.name} is kept as it is.` : '';
    if (!window.confirm(`Load ${summary}?${overflowNote}${settingsNote}${sessionNote}`)) return;

    setAuto(null);
    if (other) saveSession(template.id, { ...weeksState, session: template.id });
    setWeeksState((now) => {
      const ws: WeeksState = other ? (loadSession(other.id) ?? { session: other.id, current: 0, weeks: now.weeks.map(() => null) }) : now;
      const weeks = [...ws.weeks];
      for (const p of inRange) weeks[p.weekNumber - 1] = p.schedule;
      // a file with a Settings tab brings its settings along; an older file leaves the ones here alone
      const { settings: mine, ...rest } = ws;
      const next = uploaded ?? mine;
      return { ...rest, weeks, current: inRange[0].weekNumber - 1, ...(next && !isDefaultSettings(next) ? { settings: next } : {}) };
    });
  };

  return (
    <div>
      <header>
        <h1>
          Weekly Period Schedule Builder{' '}
          <button type="button" className="help-button" aria-label="How to use this page" title="How to use this page" onClick={() => setHelpOpen(true)}>
            ?
          </button>
        </h1>
        <p>Build a session week by week: four periods a day, Sunday to Friday. Your work is saved in this browser.</p>
        <p className="sessionbar">
          <label>
            Session:{' '}
            <select aria-label="Session" value={template.id} disabled={run !== null} onChange={(e) => switchSession(e.target.value as SessionId)}>
              {SESSION_TEMPLATES.map((t) => (
                <option key={t.id} value={t.id}>
                  {t.name}: {datesOf(t)}
                </option>
              ))}
            </select>
          </label>{' '}
          <button type="button" onClick={startOver} disabled={run !== null} title="Back to this session's own bunks, calendar and numbers.">
            Start this session over
          </button>{' '}
          <span className="muted">Each session keeps its own bunks, schedule and settings.</span>
        </p>
        <nav>
          {TABS.map((t) => (
            <button key={t.id} type="button" aria-pressed={view === t.id} onClick={() => setView(t.id)}>
              {t.label}
            </button>
          ))}
        </nav>
      </header>

      <main>
        <div className="weekbar">
          <label>
            Week:{' '}
            <select value={current} onChange={(e) => switchWeek(Number(e.target.value))}>
              {Array.from({ length: WEEK_COUNT }, (_, i) => (
                <option key={i} value={i}>
                  {weekLabel(i)} ({weekDates(template, i + 1)}){isEmpty(weeksState.weeks[i]) ? ' (empty)' : ''}
                </option>
              ))}
            </select>
          </label>{' '}
          <button type="button" onClick={handleDownload}>
            Download {weekLabel(current)} (.xlsx)
          </button>{' '}
          <button type="button" onClick={handleDownloadAll}>
            Download all weeks (.xlsx)
          </button>{' '}
          <button type="button" onClick={() => downloadSpecialists(weeksState.weeks)} title="One tab per program area: when each bunk comes, and which visit it is for them.">
            Specialist schedules (.xlsx)
          </button>{' '}
          <button type="button" onClick={handleUploadClick} disabled={run !== null}>
            Upload
          </button>
          <input ref={fileInputRef} type="file" accept=".xlsx" hidden onChange={handleFileChange} />
          {' '}
          <button type="button" onClick={resetWeek} disabled={locked}>
            Reset {weekLabel(current)}
          </button>{' '}
          <button
            type="button"
            onClick={() => setAutoOpen(true)}
            disabled={schedule.bunks.length === 0 || run !== null}
            title={schedule.bunks.length === 0 ? 'Add bunks on the Build tab first.' : undefined}
          >
            {run !== null && <span className="spinner" aria-hidden="true" />}
            {run !== null ? 'Generating...' : 'Auto generate'}
          </button>
          {run && <AutoGenerateProgress progress={run} onStop={() => runRef.current?.stop()} />}
          {auto && <AutoGenerateStatus weekNumbers={auto.weeks.map((w) => w + 1)} seed={auto.seed} onUndo={undoAutoGenerate} />}
        </div>

        {helpOpen && <HelpPanel onClose={() => setHelpOpen(false)} />}
        {autoOpen && (
          <AutoGenerateDialog
            weekNumber={current + 1}
            hasActivities={hasActivities}
            weeks={weekInfo.slice(0, template.weeks)}
            sessionWeeks={template.weeks}
            sessionName={`${template.name}, ${datesOf(template)}`}
            bigVillage={usesBigVillageSettings(settings) ? undefined : bigVillageIn(schedule.bunks.map((b) => b.name))}
            onCancel={() => setAutoOpen(false)}
            onGenerate={runAutoGenerate}
          />
        )}

        {view === 'build' && (
          <fieldset className="readonly" disabled={locked}>
            {locked && <p className="hint">This week is being generated. You can look at it, and change it once the run is over.</p>}
            <p className="bunkbar">
              Add a bunk to{' '}
              {addableVillages(template).map((v) => (
                <button key={v} type="button" disabled={run !== null} onClick={() => addBunkTo(v)} title={`Adds the next ${villageName(v)} bunk to every week of the session.`}>
                  {v}
                </button>
              ))}{' '}
              <button type="button" disabled={run !== null} onClick={fillBiggestCamp}>
                Fill in the biggest camp ({biggestCampSize(template)} bunks, {MAX_CAMPERS_PER_BUNK} campers each)
              </button>{' '}
              <span className="muted">A bunk added here goes into every week of the session.</span>
            </p>
            <BuildGrid
              bunks={schedule.bunks}
              onCell={setCell}
              onBunk={setBunkField}
              onAdd={addBunk}
              onRemove={removeBunk}
              onMove={moveBunk}
              onFillSlots={fillSlots}
              onClear={clearPeriods}
              onRemoveMarks={removeMarks}
              dayLabels={dayLabels(template, current + 1)}
              usePreviousWeek={
                current > 0
                  ? {
                      label: `Use ${weekLabel(current - 1)}'s bunks`,
                      disabled: !previousWeek || previousWeek.bunks.length === 0,
                      onClick: useLastWeekBunks,
                    }
                  : undefined
              }
            />
            {/* <DayDetails days={schedule.days} onDay={setDayField} /> */}
          </fieldset>
        )}
        {view === 'schedule' && <ScheduleView bunks={schedule.bunks} days={schedule.days} dayLabels={dayLabels(template, current + 1)} />}
        {view === 'specialists' && <SpecialistView weeks={weeksState.weeks} onDownload={() => downloadSpecialists(weeksState.weeks)} />}
        {view === 'settings' && (
          <SettingsView
            settings={settings}
            villages={[...new Set(schedule.bunks.map((b) => villageOf(b.name)))].filter(Boolean)}
            onChange={setSettings}
            onReset={() => setSettings(null)}
            disabled={run !== null}
            problems={checkSettings(settings, weeksState.weeks, template.weeks, calendarFor(template.weeks))}
            bunks={schedule.bunks}
            calendar={{ template, onApply: putCalendarOn }}
          />
        )}
        {view === 'tracking' && <TrackingView bunks={schedule.bunks} weekLabel={weekLabel(current)} schedules={allSchedules} />}
      </main>

      <footer>
        <button type="button" onClick={clearActivities} disabled={locked}>
          Clear all activities
        </button>{' '}
        <button type="button" onClick={resetToSample} disabled={locked}>
          Reset to sample
        </button>{' '}
        <a className="support" href={SUPPORT_LINK}>
          Contact support
        </a>{' '}
        <span className="version muted">Version {APP_VERSION}</span>
      </footer>
    </div>
  );
}
