import { renderToStaticMarkup } from 'react-dom/server';
import { describe, expect, it } from 'vitest';
import App from './App';
import AutoGenerateDialog from './components/AutoGenerateDialog';
import AutoGenerateProgress, { clockText, runMeasure, weekShare } from './components/AutoGenerateProgress';
import { runBudgetMs } from './autogen/config';
import AutoGenerateStatus from './components/AutoGenerateStatus';
import BuildGrid from './components/BuildGrid';
import HelpPanel from './components/HelpPanel';
import ScheduleView from './components/ScheduleView';
import TrackingView from './components/TrackingView';
import { isFirstVisit, markHelpSeen, normalize, normalizeWeeksState } from './storage';
import { newBunk, sampleSchedule } from './sample';

const noop = () => {};

describe('rendering', () => {
  const { bunks, days } = sampleSchedule();

  it('schedule view emits rowspan and colspan for merged blocks', () => {
    const merged = [newBunk('O1'), newBunk('O2'), newBunk('O3')];
    for (const b of merged) {
      b.slots[0] = 'Pool';
      b.slots[1] = 'Pool';
    }
    const html = renderToStaticMarkup(<ScheduleView bunks={merged} days={days} />);
    expect(html).toMatch(/rowSpan="3" colSpan="2"|rowspan="3" colspan="2"/i); // 3 bunks sharing a double period
  });

  it('build view has one searchable activity input per bunk per slot, plus the fill toolbar', () => {
    const html = renderToStaticMarkup(
      <BuildGrid bunks={bunks} onCell={noop} onBunk={noop} onAdd={noop} onRemove={noop} onMove={noop} onFillSlots={noop} />,
    );
    // +1 for the bulk-fill toolbar's own activity input
    expect((html.match(/class="activity-input"/g) ?? []).length).toBe(bunks.length * 24 + 1);
    expect((html.match(/role="combobox"/g) ?? []).length).toBe(bunks.length * 24 + 1);
    // day/period/village pickers in the fill toolbar are still plain selects, and so are the Clear tool's four
    expect((html.match(/<select/g) ?? []).length).toBe(3 + 4);
    // the option list only exists while a cell is open
    expect(html).not.toContain('combo-panel');
  });

  it('build view has the Clear tool: what, for whom, which day and which periods', () => {
    const html = renderToStaticMarkup(
      <BuildGrid bunks={bunks} onCell={noop} onBunk={noop} onAdd={noop} onRemove={noop} onMove={noop} onFillSlots={noop} onClear={noop} onRemoveMarks={noop} />,
    );
    for (const label of ['Clear what', 'Clear for', 'Clear day', 'Clear periods']) expect(html).toContain(`aria-label="${label}"`);
    for (const option of ['everything', 'Waterfront', 'Onondaga', 'the whole week', 'All day', 'Morning (periods 1-2)']) expect(html).toContain(`>${option}</option>`);
    expect(html).toContain('>O1</option>'); // a single bunk can be picked
    expect(html).not.toContain('Remove the yellow marks'); // nothing is marked yet
    expect(html).not.toContain('class="cleared"');
  });

  it('shows a cleared period in yellow on the Build and Schedule tabs until it is filled again', () => {
    const marked = [{ ...newBunk('O1'), cleared: [2, 5] }];
    marked[0].slots[5] = 'Pool'; // filled again: no longer shown as cleared
    const build = renderToStaticMarkup(
      <BuildGrid bunks={marked} onCell={noop} onBunk={noop} onAdd={noop} onRemove={noop} onMove={noop} onFillSlots={noop} onClear={noop} onRemoveMarks={noop} />,
    );
    expect((build.match(/class="cleared"/g) ?? []).length).toBe(1);
    expect(build).toContain('Remove the yellow marks');
    const view = renderToStaticMarkup(<ScheduleView bunks={marked} days={days} />);
    expect((view.match(/class="cleared"/g) ?? []).length).toBe(1);
  });

  it('tracking view renders', () => {
    const html = renderToStaticMarkup(
      <TrackingView bunks={bunks} weekLabel="Week 1" schedules={[{ bunks, days }]} />,
    );
    expect(html).toContain('Waterfront');
    expect(html).toContain('All bunks');
    expect(html).toContain('Whole session');
  });

  it('whole app renders without a saved schedule', () => {
    // no localStorage in node: the app must fall back to the sample
    expect(renderToStaticMarkup(<App />)).toContain('Weekly Period Schedule Builder');
  });

  it('schedule view makes filled blocks clickable and leaves empty cells alone', () => {
    const two = [newBunk('O1'), newBunk('O2')];
    two[0].slots[0] = 'Pool';
    const html = renderToStaticMarkup(<ScheduleView bunks={two} days={days} />);
    expect((html.match(/role="button"/g) ?? []).length).toBe(1);
    expect(html).toContain('aria-pressed="false"');
    expect(html).toContain('Click a block to highlight');
    expect(html).not.toContain('class="filled hl');
  });

  it('schedule view copes with zero bunks and an empty bunk', () => {
    expect(() => renderToStaticMarkup(<ScheduleView bunks={[]} days={days} />)).not.toThrow();
    expect(() => renderToStaticMarkup(<ScheduleView bunks={[newBunk()]} days={days} />)).not.toThrow();
  });
});

describe('Auto generate UI', () => {
  it('the week bar has an Auto generate button for the selected week', () => {
    expect(renderToStaticMarkup(<App />)).toMatch(/>Auto generate<\/button>/);
  });

  it('the dialog explains what will happen, and the session is picked at the top of the page', () => {
    const html = renderToStaticMarkup(<AutoGenerateDialog weekNumber={2} hasActivities={false} onCancel={noop} onGenerate={noop} />);
    expect(html).toContain('Auto generate Week 2?');
    expect(html).toContain('It reads the other weeks you have loaded');
    expect(html).toContain('The session calendar');
    expect(html).not.toContain('Session 2 (3 weeks');
    // the page opens on Setup the first time, which offers both sessions with this summer's dates
    const page = renderToStaticMarkup(<App />);
    expect(page).toMatch(/aria-pressed="true"[^>]*>Setup<\/button>/);
    expect(page).toContain('<strong>Session 1 (4 weeks)</strong><span>June 27 to July 23, 2027</span>');
    expect(page).toContain('<strong>Session 2 (3 weeks, with Color War)</strong><span>July 26 to August 15, 2027</span>');
    // the week picker and the week's file are on the tabs that show a week, not here
    expect(page).not.toContain('Week 1 (6.27 to 7.2)');
    expect(page).not.toContain('Download Week 1');
    // one way to start again, and none of the old reset buttons
    expect(page).toMatch(/>\s*Reset\s*<\/button>/);
    for (const gone of ['Reset to sample', 'Clear all activities', 'Reset Week', 'Start this session over', 'Start over']) expect(page).not.toContain(gone);
    expect(html).toContain('Generate');
    expect(html).not.toContain('already has activities');
    expect(html).not.toContain('already has activities');
  });

  it('shows no warning text after generating: just the status line, Undo and the seed', () => {
    const html = renderToStaticMarkup(<AutoGenerateStatus weekNumbers={[2]} seed={1234} onUndo={noop} />);
    expect(html).toContain('Week 2 generated');
    expect(html).toContain('Undo');
    expect(html).toContain('Seed 1234');
    expect(html).not.toContain('<details');
    expect(html).not.toContain('<li');
    expect(html).not.toMatch(/could not|short|warning|missing|unable/i);
    expect(html).not.toContain(String.fromCharCode(0x2014));
    // and the app never renders such text either
    expect(renderToStaticMarkup(<App />)).not.toMatch(/could not be met|<details/i);
  });

  it('says plainly when a week is not fully done, with how many periods are empty, and offers to keep trying', () => {
    const html = renderToStaticMarkup(
      <AutoGenerateStatus weekNumbers={[1, 2, 3, 4]} seed={7} onUndo={noop} unfinished={[{ weekNumber: 2, empty: 5 }, { weekNumber: 4, empty: 0 }]} onKeepTrying={noop} />,
    );
    expect(html).toContain('Not fully done.');
    expect(html).toContain('Week 2 has 5 empty periods, in yellow');
    expect(html).toContain('Week 4 is not complete');
    expect(html).toContain('>Keep trying</button>');
    expect(html).toContain('>Undo</button>');
    expect(html).not.toContain('generated. Check the Tracking tab'); // it does not also say it went fine
    // one period, one week
    expect(renderToStaticMarkup(<AutoGenerateStatus weekNumbers={[2]} seed={7} onUndo={noop} unfinished={[{ weekNumber: 2, empty: 1 }]} />)).toContain('Week 2 has 1 empty period, in yellow');
    // a complete run has no such line and no such button
    expect(renderToStaticMarkup(<AutoGenerateStatus weekNumbers={[2]} seed={7} onUndo={noop} unfinished={[]} onKeepTrying={noop} />)).not.toMatch(/Not fully done|Keep trying/);
  });

  it('the progress bar goes by the clock against each week\'s time limit, in a thousand stops, and says the most time left', () => {
    // a whole session: 2 minutes for a full camp and less for a smaller one; one week of four gets a quarter
    expect([runBudgetMs(12, 4, 4), runBudgetMs(21, 4, 4), runBudgetMs(24, 4, 4), runBudgetMs(27, 4, 4), runBudgetMs(27, 3, 3), runBudgetMs(27, 1, 4)]).toEqual([75_000, 75_000, 97_500, 120_000, 120_000, 30_000]);
    // four weeks of 100 seconds each: one done, the second 30 seconds in (20 from tries that are over, 10 into this one)
    const progress = { weekNumbers: [1, 2, 3, 4], states: ['done', 'working', 'waiting', 'waiting'] as ('done' | 'working' | 'waiting')[], tries: 2, startedAt: 0, spent: [40_000, 20_000, 0, 0], budgets: [100_000, 100_000, 100_000, 100_000], tryStartedAt: 50_000 };
    // most weeks come out in the first quarter of their limit, so that quarter is four fifths of a week's stretch of the bar
    expect([0, 12_500, 25_000, 62_500, 100_000, 300_000].map((used) => weekShare(used, 100_000))).toEqual([0, 0.4, 0.8, 0.9, 1, 1]);
    const measured = runMeasure(progress, 60_000);
    expect(measured?.leftAtMost).toBe(270_000);
    expect(measured?.share).toBeCloseTo((1 + weekShare(30_000, 100_000)) / 4, 10);
    const html = renderToStaticMarkup(<AutoGenerateProgress progress={progress} onStop={noop} now={60_000} />);
    expect(html).toMatch(/<progress[^>]*value="453"[^>]*max="1000"|<progress[^>]*max="1000"[^>]*value="453"/);
    expect(html).toContain('1 of 4 weeks done');
    expect(html).toContain('1:00, 4:30 more at the most');
    expect(html).toContain('Week 2: working, try 3');
    expect(html).toContain('A full camp is given up to 2 minutes for a whole session');
    // a week never counts for more than its limit, and a finished run is a full bar
    expect(runMeasure({ ...progress, spent: [0, 500_000, 0, 0] }, 60_000)?.share).toBe(2 / 4);
    expect(runMeasure({ ...progress, states: ['done', 'done', 'done', 'done'] }, 60_000)).toEqual({ share: 1, leftAtMost: 0 });
    // one week has a real bar too
    const one = { weekNumbers: [3], states: ['working'] as ('done' | 'working' | 'waiting')[], tries: 0, startedAt: 0, spent: [0], budgets: [45_000], tryStartedAt: 0 };
    expect(renderToStaticMarkup(<AutoGenerateProgress progress={one} onStop={noop} now={9000} />)).toMatch(/value="640"/);
  });

  it('names every week it generated in the status line', () => {
    expect(renderToStaticMarkup(<AutoGenerateStatus weekNumbers={[1, 2, 3, 4]} seed={1} onUndo={noop} />)).toContain('Weeks 1 to 4 generated');
    expect(renderToStaticMarkup(<AutoGenerateStatus weekNumbers={[1, 3]} seed={1} onUndo={noop} />)).toContain('Weeks 1 and 3 generated');
  });

  it('shows a run in progress: weeks done out of the total, where each week stands, the clock and Stop', () => {
    const progress = { weekNumbers: [1, 2, 3, 4], states: ['done', 'done', 'working', 'waiting'] as const, tries: 1, startedAt: 0 };
    const html = renderToStaticMarkup(<AutoGenerateProgress progress={{ ...progress, states: [...progress.states] }} onStop={noop} now={75_000} />);
    expect(html).toContain('2 of 4 weeks done');
    expect(html).toMatch(/<progress[^>]*value="2"[^>]*max="4"|<progress[^>]*max="4"[^>]*value="2"/);
    expect(html).toContain('Week 1: done');
    expect(html).toContain('Week 3: working, try 2');
    expect(html).toContain('Week 4: waiting');
    expect(html).toContain('1:15');
    expect(html).toContain('>Stop</button>');
    expect(html).not.toMatch(/fail|error|short|warning/i); // it never says what went wrong, only that it is trying again
    // one week: nothing to count, so the bar only shows that it is busy
    const one = renderToStaticMarkup(<AutoGenerateProgress progress={{ weekNumbers: [3], states: ['working'], tries: 0, startedAt: 0 }} onStop={noop} now={5000} />);
    expect(one).toContain('0 of 1 week done');
    expect(one).not.toMatch(/<progress[^>]*value=/);
    expect(one).toContain('Week 3: working');
    expect(clockText(600_000)).toBe('10:00');
  });

  it('has a "?" in the header that opens the how-to, written plainly and without long dashes', () => {
    expect(renderToStaticMarkup(<App />)).toContain('aria-label="How to use this page"');
    const html = renderToStaticMarkup(<HelpPanel onClose={noop} />);
    for (const heading of ['How to use this page', 'The tabs', 'Setting up and building a session', 'Changing things by hand', 'Settings', 'Saving, sharing and printing', 'Good to know']) {
      expect(html).toContain(`>${heading}</h`);
    }
    // the rules that are always kept are not listed for now
    expect(html).not.toContain('The rules that are always kept');
    expect(html).not.toContain('No bunk has the same kind of period two days in a row.');
    expect(html).toContain('Specialist schedules');
    expect(html).not.toMatch(/—|–/); // no em or en dashes
    expect(html).not.toMatch(/director/i);
    expect(renderToStaticMarkup(<App />)).toMatch(/<footer>.*Version \d+\.\d+\.\d+<.*<\/footer>/s); // and which version this is
    // a way to reach a person, in the how-to and at the foot of every page
    expect(html).toContain('href="mailto:joshcohn27@gmail.com');
    expect(renderToStaticMarkup(<App />)).toMatch(/<footer>.*href="mailto:joshcohn27@gmail\.com[^"]*"[^>]*>Contact support<\/a>.*<\/footer>/s);
  });

  it('opens the how-to by itself on the very first visit to the page in a browser, and never again', () => {
    const opened = (): boolean => renderToStaticMarkup(<App />).includes('id="help-title"');
    // no browser storage at all (as here in node): it stays closed rather than opening every time
    expect(isFirstVisit()).toBe(false);
    expect(opened()).toBe(false);
    const store = new Map<string, string>();
    const fake = { getItem: (k: string) => store.get(k) ?? null, setItem: (k: string, v: string) => void store.set(k, v) };
    (globalThis as { localStorage?: unknown }).localStorage = fake;
    try {
      expect(isFirstVisit()).toBe(true);
      expect(opened()).toBe(true); // the first time: the how-to is on the page
      markHelpSeen();
      expect(isFirstVisit()).toBe(false);
      expect(opened()).toBe(false); // every time after: only the ? is there
      expect(renderToStaticMarkup(<App />)).toContain('aria-label="How to use this page"');
      // a browser that refuses storage does not throw, and does not nag
      fake.getItem = () => {
        throw new Error('blocked');
      };
      expect(isFirstVisit()).toBe(false);
    } finally {
      delete (globalThis as { localStorage?: unknown }).localStorage;
    }
  });

  it('offers one week or the whole session, and the two options', () => {
    const info = { hasBunks: true, hasActivities: false, built: false };
    const html = renderToStaticMarkup(<AutoGenerateDialog weekNumber={2} hasActivities={false} weeks={[info, info, info, info]} onCancel={noop} onGenerate={noop} />);
    expect(html).toContain('Just Week 2');
    expect(html).toContain('The whole session, week by week');
    expect(html).toContain('keep Bike Trip and Tiyul where they are');
    expect(html).toContain('Count what the other');
    expect(html).toContain('will not be given a third');
  });

  it('asks what to do with existing activities only when there are some', () => {
    const html = renderToStaticMarkup(<AutoGenerateDialog weekNumber={3} hasActivities onCancel={noop} onGenerate={noop} />);
    expect(html).toContain('Week 3 already has activities in it. What should happen to them?');
    expect(html).toContain('build around it');
    expect(html).toContain('Week 3 is cleared first');
    expect(html).toContain('keep Bike Trip and Tiyul where they are');
    expect((html.match(/type="radio"/g) ?? []).length).toBe(2);
    expect(html).not.toContain(String.fromCharCode(0x2014));
  });
});

describe('normalize (saved data)', () => {
  it('repairs short slot arrays and keeps write-in activities', () => {
    const s = normalize({ bunks: [{ id: 'a', name: 'O1', slots: ['Pool', 'Extra Craft Time'] }], days: [] })!;
    expect(s.bunks[0].slots).toHaveLength(24);
    expect(s.bunks[0].slots[0]).toBe('Pool');
    expect(s.bunks[0].slots[1]).toBe('Extra Craft Time');
    expect(s.bunks[0].slots[2]).toBe('');
    expect(s.days).toHaveLength(6);
  });

  it('rejects garbage', () => {
    expect(normalize(null)).toBeNull();
    expect(normalize({ nope: 1 })).toBeNull();
  });
});

describe('normalizeWeeksState (saved multi-week data)', () => {
  it('pads to 4 week slots and clamps the current index', () => {
    const raw = { weeks: [{ bunks: [{ id: 'a', name: 'O1', slots: ['Pool'] }], days: [] }], current: 9 };
    const state = normalizeWeeksState(raw)!;
    expect(state.weeks).toHaveLength(4);
    expect(state.weeks[0]!.bunks[0].name).toBe('O1');
    expect(state.weeks[1]).toBeNull();
    expect(state.current).toBe(0);
  });

  it('rejects garbage', () => {
    expect(normalizeWeeksState(null)).toBeNull();
    expect(normalizeWeeksState({ nope: 1 })).toBeNull();
  });
});
