import { createElement } from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { describe, expect, it } from 'vitest';
import { isGuest } from './autofill';
import { SESSION_1, SESSION_2 } from './autogen/sessionCalendar';
import { defaultSettings, normalizeSettings, templateSettings } from './autogen/settings';
import CalendarSettings from './components/CalendarSettings';
import SetupView from './components/SetupView';
import SettingsView from './components/SettingsView';
import TrackingView from './components/TrackingView';
import { checkSettings } from './autogen/feasibility';
import { generateRun } from './autogen/session';
import { ropesOutlook } from './autogen/ropesRoom';
import { applySettings, bigVillageIn, coreOf, defaultCore, sharingOf, usesBigVillageSettings, withBigVillageSettings, withCore } from './autogen/settings';
import { slotAt } from './autogen/history';
import { sessionTargetOf } from './autogen/planner';
import { validateWeek } from './autogen/validate';
import AutoGenerateDialog from './components/AutoGenerateDialog';
import StartOverDialog from './components/StartOverDialog';
import { newBunk } from './sample';
import App from './App';
import { MAX_BUNKS_IN_CAMP, biggestCampSize, datesOf, dayLabels, startSession, startedOver, templateOf, weekDates, withBiggestCamp, withBunkAdded, withCalendar, rosterOf, withBunkChanged, withBunkMoved, withBunkRemoved } from './session';
import { normalizeWeeksState } from './storage';
import type { Schedule } from './types';

const noop = () => {};

describe('starting a session from its template', () => {
  it('Session 1: four weeks of its bunks, the 2027 dates, and the calendar already on the schedule', () => {
    const s = startSession(SESSION_1);
    expect(s.session).toBe('session1');
    expect(s.weeks.map((w) => w?.bunks.length ?? 0)).toEqual([22, 22, 22, 22]);
    expect(s.settings).toBeUndefined(); // Session 1 has the app's own numbers
    expect((s.weeks[0] as Schedule).bunks[0].slots.slice(0, 5)).toEqual(['Opening Day', 'Opening Day', 'Opening Day', 'Opening Day', '']);
    expect((s.weeks[3] as Schedule).bunks.find((b) => b.name === 'S1')!.slots[0]).toBe('S-Day');
    expect(datesOf(SESSION_1)).toBe('June 27 to July 23, 2027');
    expect(dayLabels(SESSION_1, 1)).toEqual(['Sunday 6.27', 'Monday 6.28', 'Tuesday 6.29', 'Wednesday 6.30', 'Thursday 7.1', 'Friday 7.2']);
    expect(weekDates(SESSION_1, 4)).toBe('7.18 to 7.23');
  });

  it('Session 2: three weeks, Taste of CSL in week 1 only, its own numbers, and it survives being saved', () => {
    const s = startSession(SESSION_2);
    // 4 Taste, 3 Onondaga, 4 Cayuga (Taste's cabins come out of those two villages), 5 Seneca, 5 Mohawk, 4 Tusc
    expect(s.weeks.map((w) => w?.bunks.length ?? 0)).toEqual([25, 21, 21, 0]);
    expect((s.weeks[0] as Schedule).bunks.filter((b) => isGuest(b.name)).map((b) => b.name)).toEqual(['TC1', 'TC2', 'TC3', 'TC4']);
    expect((s.weeks[1] as Schedule).bunks.some((b) => isGuest(b.name))).toBe(false);
    expect(s.settings?.areas.Yoga).toMatchObject({ min: 1, max: 2 });
    // opening day is Monday July 26: the Sunday before it has no periods
    expect(dayLabels(SESSION_2, 1).slice(0, 3)).toEqual(['Sunday 7.25', 'Monday 7.26', 'Tuesday 7.27']);
    expect((s.weeks[2] as Schedule).bunks[0].slots[4]).toBe('Color War');
    const back = normalizeWeeksState(JSON.parse(JSON.stringify(s)));
    expect(back?.session).toBe('session2');
    expect(back?.settings).toEqual(templateSettings(SESSION_2));
    expect(templateOf(undefined)).toBe(SESSION_1); // a schedule from before sessions were told apart
  });

  it('the settings check knows the calendar: Session 1 adds up, Session 2 is told what will come up short, and that ropes for everyone does not fit', () => {
    const one = startSession(SESSION_1);
    applySettings(templateSettings(SESSION_1));
    expect(checkSettings(templateSettings(SESSION_1), one.weeks, 4, SESSION_1.events)).toEqual([]);
    const two = startSession(SESSION_2);
    applySettings(templateSettings(SESSION_2));
    // Session 2 starts with numbers that fit it: ropes once, league twice a week, Ceramics once
    expect(checkSettings(templateSettings(SESSION_2), two.weeks, 3, SESSION_2.events)).toEqual([]);
    // asked for what Session 1 has, it is told what will come up short
    const asked = withCore(templateSettings(SESSION_2), { ...coreOf(templateSettings(SESSION_2)), ropesPerSession: 2, leaguePerWeek: 3 });
    applySettings(asked);
    const found = checkSettings(asked, two.weeks, 3, SESSION_2.events);
    expect(found.length).toBeGreaterThan(1);
    // everything the calendar squeezes is "will come up short"; ropes is the one thing it calls not possible, because one
    // group goes at a time and the session has fewer half-days than these bunks need
    const ropes = found.filter((p) => p.text.startsWith('Ropes'));
    expect(ropes).toHaveLength(1);
    expect(ropes[0].level).toBe('no');
    expect(ropes[0].text).toContain('one group is at ropes in a half-day');
    expect(ropes[0].fix).toContain('campers at once at ropes');
    expect(found.filter((p) => !p.text.startsWith('Ropes')).every((p) => p.level === 'short')).toBe(true);
    const html = renderToStaticMarkup(createElement(SettingsView, { settings: asked, villages: ['O'], onChange: noop, onReset: noop, problems: found }));
    expect(html).toContain('Will come up short.');
    expect((html.match(/Not possible\./g) ?? []).length).toBe(1);
    // Session 1 as it starts has room for everyone's ropes; its biggest camp does not, and the page says so
    applySettings(templateSettings(SESSION_1));
    expect(ropesOutlook(one.weeks, 4)).toMatchObject({ halfDays: 28, groups: 24, fits: true });
    const big = withBiggestCamp(one);
    applySettings(withBigVillageSettings(templateSettings(SESSION_1)));
    expect(ropesOutlook(big.weeks, 4)).toMatchObject({ halfDays: 28, groups: 28, fits: false, campersToFit: 45 });
    expect(checkSettings(withBigVillageSettings(templateSettings(SESSION_1)), big.weeks, 4, SESSION_1.events).some((p) => p.text.startsWith('Ropes will not come out for everyone'))).toBe(true);
    applySettings();
  });

  it('the tracking grid is marked up for the same pointer highlighting as the sharing grid', () => {
    const week = startSession(SESSION_1).weeks[0] as Schedule;
    const html = renderToStaticMarkup(createElement(TrackingView, { bunks: week.bunks, weekLabel: 'Week 1', schedules: [week] }));
    expect(html).toContain('class="tracking-grid"');
    expect(html).not.toContain('pair-hover'); // nothing is lit until the pointer is on a box
  });

  it('when ropes for everyone fits, a generated session gives every bunk its ropes', async () => {
    const start = startSession(SESSION_1);
    expect(ropesOutlook(start.weeks, 4).fits).toBe(true);
    const run = await generateRun({
      weeks: start.weeks,
      steps: [0, 1, 2, 3].map((index) => ({ index, mode: 'fill-empty' as const })),
      roster: (start.weeks[0] as Schedule).bunks,
      sessionWeeks: 4,
      keepTrips: true,
      useOtherWeeks: true,
      seed: 7,
      calendar: true,
      maxWeekMs: 120_000,
      maxMsPerTry: 40_000,
    });
    const ropes: Record<string, number> = {};
    for (const w of run?.weeks ?? []) for (const b of w?.bunks ?? []) ropes[b.name] = (ropes[b.name] ?? 0) + b.slots.filter((l) => l === 'Low Ropes' || l === 'High Ropes').length / 2;
    expect(Object.values(ropes).filter((n) => n < 2)).toEqual([]);
  }, 600_000);

  it('Start over: a week or the whole session, keeping the bunks and the settings or not', () => {
    // a session that has been worked on: a renamed bunk, a changed count, things in the periods, changed settings
    const worked = startSession(SESSION_1);
    for (const w of worked.weeks) {
      const b = (w as Schedule).bunks[1];
      b.name = 'O2';
      b.count = '14';
      for (const x of (w as Schedule).bunks) x.slots[slotAt(2, 0)] = 'Music';
    }
    (worked.weeks[1] as Schedule).bunks.push(newBunk('O6', '6th', '9'));
    const mine = normalizeSettings({ ...defaultSettings(), areas: { ...defaultSettings().areas, Teva: { ...defaultSettings().areas.Teva, min: 1, max: 1 } } });
    const state = { ...worked, settings: mine, current: 1 };

    // just week 2, bunks kept: its periods are emptied, the calendar is back, the extra bunk and the count stay, nothing else moves
    const week = startedOver(state, { scope: 'week', keepBunks: true, keepSettings: true });
    const w2 = week.weeks[1] as Schedule;
    expect(w2.bunks.map((b) => b.name)).toContain('O6');
    expect(w2.bunks[1].count).toBe('14');
    expect(w2.bunks[0].slots[slotAt(2, 0)]).toBe('');
    expect(w2.bunks[0].slots[slotAt(2, 2)]).toBe('Tiyul'); // Onondaga, week 2, Tuesday afternoon
    expect(w2.bunks.find((b) => b.name === 'O6')!.slots[slotAt(2, 2)]).toBe('Tiyul');
    expect(week.weeks[0]).toBe(state.weeks[0]);
    expect(week.settings).toBe(mine);

    // just week 2, bunks not kept: the session's own bunks for that week
    const own = startedOver(state, { scope: 'week', keepBunks: false, keepSettings: true }).weeks[1] as Schedule;
    expect(own.bunks.map((b) => b.name)).not.toContain('O6');
    expect(own.bunks).toHaveLength(22);
    expect(own.bunks[1].count).toBe('12');

    // the whole session, everything kept: every week emptied, calendar back, bunks and settings as they were
    const all = startedOver(state, { scope: 'session', keepBunks: true, keepSettings: true });
    expect((all.weeks[0] as Schedule).bunks[3].slots[slotAt(2, 0)]).toBe('');
    expect((all.weeks[0] as Schedule).bunks[3].slots[0]).toBe('Opening Day');
    expect((all.weeks[1] as Schedule).bunks.map((b) => b.name)).toContain('O6');
    expect(all.settings).toBe(mine);

    // the whole session, nothing kept: exactly as the session starts
    const clean = startedOver(state, { scope: 'session', keepBunks: false, keepSettings: false });
    const begin = startSession(SESSION_1);
    expect(clean.settings).toBeUndefined();
    expect(clean.weeks.map((w) => w?.bunks.map((b) => [b.name, b.grades, b.count, b.slots]))).toEqual(begin.weeks.map((w) => w?.bunks.map((b) => [b.name, b.grades, b.count, b.slots])));

    // the dialog says what will happen before anything does
    const html = renderToStaticMarkup(createElement(StartOverDialog, { weekNumber: 2, sessionName: 'Session 1 (4 weeks)', onCancel: noop, onStartOver: noop }));
    // three plain choices: clear everything, clear the week, or back to the base template
    expect(html).toContain('Clear everything: every week of the session');
    expect(html).toContain('Clear only Week 2');
    expect(html).toContain('Reset to the base template for Session 1 (4 weeks)');
    expect(html).not.toContain('Keep my');
    expect(html).toContain('Every period of every week of Session 1 (4 weeks) is emptied. Your bunks and your settings stay.');
    expect(html).toContain('This cannot be undone.');
  });

  it('offers suggested settings when a village has six bunks, and never applies them by itself', () => {
    const six = ['O1', 'O2', 'O3', 'O4', 'O5', 'O6'].map((n) => newBunk(n, '5th', '10'));
    let next: ReturnType<typeof defaultSettings> | null = null;
    // the numbers the app starts with fit a big village, so the offer is only for settings that were lowered
    const lowered = withCore(defaultSettings(), { ...defaultCore(), athletics: { ...defaultCore().athletics, villagePerDay: 2 } });
    const html = renderToStaticMarkup(createElement(SettingsView, { settings: lowered, villages: ['O'], onChange: (s) => (next = s), onReset: noop, bunks: six }));
    expect(html).toContain('Use the suggested settings');
    expect(next).toBeNull();
    expect(renderToStaticMarkup(createElement(SettingsView, { settings: lowered, villages: ['O'], onChange: noop, onReset: noop, bunks: six.slice(0, 5) }))).not.toContain('suggested settings');
    expect(renderToStaticMarkup(createElement(SettingsView, { settings: defaultSettings(), villages: ['O'], onChange: noop, onReset: noop, bunks: six }))).not.toContain('suggested settings');
  });

  it('Session 2: Ceramics once for the older villages, one ropes for everybody, and for Tusc that ropes is High, because it is the same campers as Session 1', () => {
    const two = templateSettings(SESSION_2);
    expect(two.villageTargets).toEqual({ Ropes: { T: 1 } });
    expect(two.areas.Ceramics.villages).toEqual({ O: 0, C: 0, S: 1, M: 1, T: 1 }); // none for the younger villages in the short session
    expect(coreOf(two)).toMatchObject({ ropesPerSession: 1, leaguePerWeek: 2 });
    expect(two.ropesStartHigh).toEqual(['T']);
    applySettings(two);
    expect(sessionTargetOf('T', 3, 'Ceramics')).toBe(1);
    expect(sessionTargetOf('S', 3, 'Ceramics')).toBe(1);
    expect(sessionTargetOf('T', 3, 'Ropes')).toBe(1);
    expect(sessionTargetOf('S', 3, 'Ropes')).toBe(1);
    // a first ropes block for Tusc is High Ropes in this session, and Low Ropes for everybody else
    const week = startSession(SESSION_2).weeks[1] as Schedule;
    const put = (name: string, label: string) => {
      const b = week.bunks.find((x) => x.name === name)!;
      b.slots[slotAt(5, 2)] = label;
      b.slots[slotAt(5, 3)] = label;
    };
    put('T1', 'High Ropes');
    put('O1', 'Low Ropes');
    const ropes = validateWeek({ current: 1, weeks: [null, week, null, null] }, 2, 3).filter((v) => v.rule === 'H6');
    expect(ropes).toEqual([]);
    put('T1', 'Low Ropes');
    expect(validateWeek({ current: 1, weeks: [null, week, null, null] }, 2, 3).filter((v) => v.rule === 'H6').map((v) => v.bunk)).toEqual(['T1']);
    applySettings();
    expect(sessionTargetOf('T', 4, 'Ropes')).toBe(2); // Session 1: low, then high
    expect([sessionTargetOf('O', 4, 'Ceramics'), sessionTargetOf('S', 4, 'Ceramics')]).toEqual([1, 2]); // Session 1: the younger villages once, the older twice
    expect(templateSettings(SESSION_1).villageTargets).toBeUndefined();
  });

  it('the settings for big villages: what they are, and when they count as in use', () => {
    expect(bigVillageIn(['O1', 'O2', 'O3', 'O4', 'O5', 'C1'])).toBeUndefined();
    expect(bigVillageIn(['C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'O1'])).toBe('C');
    expect(bigVillageIn(['TC1', 'TC2', 'TC3', 'TC4', 'TC5', 'TC6', 'T1'])).toBeUndefined(); // Taste of CSL is not Tusc
    expect(usesBigVillageSettings(defaultSettings())).toBe(true); // the numbers the app starts with are the ones a big village needs
    const lowered = withCore(defaultSettings(), { ...defaultCore(), athletics: { ...defaultCore().athletics, villagePerDay: 2 } });
    expect(usesBigVillageSettings(lowered)).toBe(false);
    const big = withBigVillageSettings(lowered);
    expect(usesBigVillageSettings(big)).toBe(true);
    expect(coreOf(big).athletics).toMatchObject({ atOnce: 3, villagePerDay: 3 }); // never four at once
    // a file saved when four was allowed is read as three
    expect(coreOf(normalizeSettings({ ...defaultSettings(), core: { ...defaultCore(), athletics: { atOnce: 4, villagePerDay: 3, maxPerWeek: 3 } } })).athletics.atOnce).toBe(3);
    expect(big.areas.Ceramics).toMatchObject({ atOnce: 2, villagePerDay: 3 });
    expect(big.areas.Teva.villagePerDay).toBe(3);
    expect(sharingOf(big).within).toBe('village');
    expect(big.areas.Teva.min).toBe(defaultSettings().areas.Teva.min); // how often is not touched
    // the dialog offers them, ticked, when a village has six bunks and they are not in use
    const offered = renderToStaticMarkup(createElement(AutoGenerateDialog, { weekNumber: 1, hasActivities: false, bigVillage: 'C', onCancel: noop, onGenerate: noop }));
    expect(offered).toContain('Use the settings for big villages');
    expect(renderToStaticMarkup(createElement(AutoGenerateDialog, { weekNumber: 1, hasActivities: false, onCancel: noop, onGenerate: noop }))).not.toContain('big villages');
  });

  it('adds a bunk to a village in every week with one click, and fills in the biggest camp', () => {
    const start = startSession(SESSION_1);
    const more = withBunkAdded(start, 'C');
    for (const w of more.weeks) {
      const names = (w as Schedule).bunks.map((b) => b.name);
      expect(names.filter((n) => n.startsWith('C'))).toEqual(['C1', 'C2', 'C3', 'C4', 'C5']);
      expect(names[names.indexOf('C5') + 1]).toBe('S1'); // after the last Cayuga bunk, before Seneca
    }
    // the new bunk has the calendar on its week like everybody else, and a grade to start from
    const c5 = (more.weeks[1] as Schedule).bunks.find((b) => b.name === 'C5')!;
    expect(c5.slots[slotAt(4, 2)]).toBe('Tiyul');
    expect(c5.grades).toBe('6th');
    expect((more.weeks[3] as Schedule).bunks.find((b) => b.name === 'C5')!.slots[0]).toBe('C-Day');
    expect((start.weeks[0] as Schedule).bunks).toHaveLength(22); // what was handed in is not changed

    // the biggest Session 1 camp: 5 Onondaga, 6 Cayuga, 6 Seneca, 6 Mohawk, 4 Tusc, 15 campers each
    const big = withBiggestCamp(start);
    expect(biggestCampSize(SESSION_1)).toBe(27);
    for (const w of big.weeks) {
      const bunks = (w as Schedule).bunks;
      const count = (v: string) => bunks.filter((b) => b.name.startsWith(v)).length;
      expect([count('O'), count('C'), count('S'), count('M'), count('T')]).toEqual([5, 6, 6, 6, 4]);
      expect(bunks.every((b) => b.count === '15')).toBe(true);
    }
    expect((big.weeks[0] as Schedule).bunks.find((b) => b.name === 'O1')!.slots[0]).toBe('Opening Day'); // the rows that were there are kept
    expect(withBiggestCamp(big)).toEqual(big); // nothing more to add
    // Session 2: Taste of CSL is in week 1 only, and the other weeks have no such bunks
    const two = withBiggestCamp(startSession(SESSION_2));
    expect((two.weeks[0] as Schedule).bunks.filter((b) => isGuest(b.name))).toHaveLength(4);
    expect((two.weeks[1] as Schedule).bunks.filter((b) => isGuest(b.name))).toHaveLength(0);
    // the camp has 27 cabins: with Taste in four of them, week 1 is full, and the other weeks have the 23 that stay
    expect((two.weeks[0] as Schedule).bunks).toHaveLength(MAX_BUNKS_IN_CAMP);
    expect((two.weeks[1] as Schedule).bunks).toHaveLength(23);
    expect(biggestCampSize(SESSION_2)).toBe(27);
    // and nothing more can be added once a week is full
    expect(withBunkAdded(two, 'O')).toBe(two);
    expect(withBunkAdded(big, 'T')).toBe(big);
    expect(two.weeks[3]).toBeNull();
    // the page offers both
    const page = renderToStaticMarkup(createElement(App));
    expect(page).toContain('aria-label="Add a bunk to Onondaga"');
    expect(page).toContain('Fill in the biggest camp');
    expect(page).toContain('22 of 27 cabins');
  });

  it('the Setup tab changes, moves and removes a bunk in every week of the session', () => {
    const s = startSession(SESSION_2);
    const names = (state: typeof s, week: number): string[] => (state.weeks[week] as Schedule).bunks.map((b) => b.name);
    const o2 = rosterOf(s).find((b) => b.name === 'O2')!;
    // week 1 has Taste of CSL in front, the other weeks do not: the bunk is found by its name there
    const renamed = withBunkChanged(withBunkChanged(s, o2.id, 'count', '15'), o2.id, 'grades', '5th');
    for (const week of [0, 1, 2]) expect((renamed.weeks[week] as Schedule).bunks.find((b) => b.name === 'O2')).toMatchObject({ grades: '5th', count: '15' });
    const moved = withBunkMoved(s, o2.id, 1);
    for (const week of [0, 1, 2]) expect(names(moved, week).filter((n) => n.startsWith('O'))).toEqual(['O1', 'O3', 'O2']);
    const gone = withBunkRemoved(s, o2.id);
    for (const week of [0, 1, 2]) expect(names(gone, week)).not.toContain('O2');
    expect(names(gone, 0)).toHaveLength(names(s, 0).length - 1);
    expect(s.weeks.map((w) => w?.bunks.length)).toEqual(startSession(SESSION_2).weeks.map((w) => w?.bunks.length)); // nothing is changed in place
    // the page: the steps in order, the villages by name, and the files at the bottom
    const html = renderToStaticMarkup(
      createElement(SetupView, {
        template: SESSION_2,
        templates: [SESSION_1, SESSION_2],
        onSession: noop,
        bunks: rosterOf(s),
        onBunk: noop,
        onAddTo: noop,
        onRemove: noop,
        onMove: noop,
        onFillBiggest: noop,
        problems: [],
        onOpenSettings: noop,
        onAutoGenerate: noop,
        onOpenBuild: noop,
        onUpload: noop,
        onDownloadAll: noop,
        onStartOver: noop,
      }),
    );
    const order = ['</span> Session', '</span> Bunks', '</span> Numbers and calendar', '</span> Build the schedule', 'Files</h3>'].map((t) => html.indexOf(t));
    expect(order.every((at, i) => at > 0 && (i === 0 || at > order[i - 1]))).toBe(true);
    for (const village of ['Taste', 'Onondaga', 'Cayuga', 'Seneca', 'Mohawk', 'Tusc']) expect(html).toContain(`>${village} <span`);
    expect(html).toContain('Taste of CSL is in camp for week 1 only.');
    expect(html).toContain('The numbers add up for these bunks.');
    expect(html).toContain('Upload a schedule (.xlsx)');
    // one plain way to start again, at the top of the page
    expect(html.indexOf('Reset\n')).toBeLessThan(html.indexOf('</span> Session'));
    expect(html).not.toContain('Start over');
  });

  it('a calendar line that was moved on the Settings tab goes on the schedule where it was put', () => {
    const s = startSession(SESSION_1);
    // clear week 3 and move Mass Program to all of Tuesday in week 3 only
    const cleared = { ...s, weeks: s.weeks.map((w, i) => (i === 2 && w ? { ...w, bunks: w.bunks.map((b) => ({ ...b, slots: b.slots.map(() => '') })) } : w)) };
    const calendar = [{ label: 'Mass Program', who: 'camp', week: 3, day: 2, periods: [0, 1, 2, 3] }];
    const settings = normalizeSettings({ ...defaultSettings(), calendar });
    expect(settings.calendar).toEqual(calendar);
    const html = renderToStaticMarkup(createElement(CalendarSettings, { settings, template: SESSION_1, villages: ['O', 'T'], onChange: noop, onApply: noop }));
    expect(html).toContain('Session calendar');
    expect(html).toContain('Tuesday 7.13');
    expect(html).toContain('Whole camp');
    expect(html).toContain('Put the calendar on the schedule now');
    // with nothing changed it shows the template: Visitor Day is on it
    expect(renderToStaticMarkup(createElement(CalendarSettings, { settings: defaultSettings(), template: SESSION_1, villages: ['O'], onChange: noop, onApply: noop }))).toContain('Visitor&#x27;s Day');
    expect(withCalendar(cleared).weeks[2]?.bunks[0].slots[0]).toBe('All Camp Clean Up'); // the template, while nothing is in force
  });
});
